# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file into the container at /app
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the working directory contents into the container at /app
COPY . .

# Set environment variables (these will be overridden by docker-compose)
ENV KAFKA_BROKER=${KAFKA_BROKER}
ENV TOPIC=${TOPIC}

# Run producer.py when the container launches
CMD ["python", "-u", "producer.py"]
