services:
  # Zookeeper service required for Kafka coordination
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes  # Allow anonymous connections for simplicity
    ports:
      - "2181:2181"

  # Kafka broker service
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes  # Allow plaintext for testing
    ports:
      - "9092:9092"  # Internal communication
      - "9093:9093"  # External communication

  # Producer service that sends messages continuously
  producer:
    build: ./producer  # Build from Dockerfile in 'producer' directory
    image: kafka-producer:latest
    container_name: kafka-producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPIC=test-topic

  # Consumer service that subscribes to the topic and verifies messages
  consumer_from_oldest:
    build: 
      context: ./consumer  # Build from Dockerfile in directory
      dockerfile: consumer_fromOldest.dockerfile
    image: consumer_from_oldest:latest
    container_name: consumer_from_oldest
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPIC=test-topic

  consumer_from_newest:
    build: 
      context: ./consumer  # Build from Dockerfile in directory
      dockerfile: consumer_fromNewest.dockerfile
    image: consumer_from_newest:latest
    container_name: consumer_from_newest
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPIC=test-topic

  consumer_batch_message:
    build: 
      context: ./consumer  # Build from Dockerfile in directory
      dockerfile: consumer_batchMessage.dockerfile
    image: consumer_batch_message:latest
    container_name: consumer_batch_message
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - TOPIC=test-topic